additionalProperties:
  formFields:
    - default: 4224
      edit: true
      envKey: PANEL_APP_PORT_HTTP
      labelZh: 端口
      labelEn: Port
      label:
        zh: 端口
        en: Port
      required: true
      rule: paramPort
      type: number

    - default: dbx_password
      edit: true
      envKey: PANEL_PG_PASSWORD
      labelZh: PostgreSQL 密码
      labelEn: PostgreSQL Password
      label:
        zh: PostgreSQL 密码
        en: PostgreSQL Password
      required: true
      rule: paramComplexity
      type: password
      random: true

    - default: ""
      edit: true
      envKey: PANEL_CONNECTION_SECRET_KEY
      labelZh: 连接凭据加密密钥
      labelEn: Connection Secret Encryption Key
      label:
        zh: 连接凭据加密密钥
        en: Connection Secret Encryption Key
      required: true
      type: password
